name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "FRONT_END_URL=${{ secrets.FRONT_END_URL }}" >> .env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRE=${{ secrets.JWT_EXPIRE }}" >> .env
          echo "SEND_GRID_API_KEY=${{ secrets.SEND_GRID_API_KEY }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test --if-present

      # Add a step to update AWS Secrets Manager
      - name: Update AWS Secrets Manager
        run: |
          aws secretsmanager update-secret --secret-id JWT_SECRET --secret-string '{"JWT_SECRET":"${{ secrets.JWT_SECRET }}"}' --region us-west-2
          aws secretsmanager update-secret --secret-id MONGODB_URL --secret-string '{"MONGODB_URL":"${{ secrets.MONGODB_URL }}"}' --region us-west-2
          aws secretsmanager update-secret --secret-id SEND_GRID_API_KEY --secret-string '{"SEND_GRID_API_KEY":"${{ secrets.SEND_GRID_API_KEY }}"}' --region us-west-2
          # Add any other secrets you'd like to update similarly

      - name: Show Runner Info
        run: |
          echo "Running on $(hostname)"
          node -v
          npm -v
